spring:
  application:
    name: yourJOB
  datasource:
    username: root
    password: user
    testwhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 9000

security:
  jwt:
    secret: secret

## mail configuration ##
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=yourmail.hotmail.com
#spring.mail.password=YourPassword
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
