spring:
  datasource:
    url: jdbc:mysql://localhost:3307/yourjobTest?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  data:
    mongodb:
      host: localhost
      port: 27017
      database: auditDB
      repositories:
        enabled: true
    
  