spring:
  application:
    name: yourJOB
  datasource:
    username: root
    password: user
    testwhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email}
    password: ${emailPassword}
    sign: YourJob Team
    location: Casablanca
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 9000

security:
  public:
    endpoint: /my/pro/job/api-docs/**,/my/pro/job/swagger-ui/**,/my/pro/job/account/register,/my/pro/job/account/reset
  jwt:
    secret: secret

springdoc:
  swagger-ui:
    path: /my/pro/job/swagger-ui
  api-docs:
    path: /my/pro/job/api-docs
    
